id: IDFC7BAD9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T06:24:27+00:00'
last_modified: '2022-06-07T17:01:24.727461+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD152281
  title: རྒྱལ་དབང་སྐུ་ཕྲེང་དང་པོ་ནས་བཞི་པའི་བར་གྱི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    A02C:
      image_group_id: I2PD17651
      title: ''
      total_pages: 676
      order: 1
      base_file: A02C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
