id: P003015
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD152281
  title: རྒྱལ་དབང་སྐུ་ཕྲེང་དང་པོ་ནས་བཞི་པའི་བར་གྱི་རྣམ་ཐར།
  author: ''
  volumes:
    5275791b476e4bbb893c3f6a13788f06:
      image_group_id: I2PD17651
      title: ''
      volume_number: 1
      total_pages: 676
