id: P003015
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 10:34:28.389156
source_metadata:
  id: bdr:W1PD152281
  title: རྒྱལ་དབང་སྐུ་ཕྲེང་དང་པོ་ནས་བཞི་པའི་བར་གྱི་རྣམ་ཐར།
  author: ''
  volumes:
    5275791b476e4bbb893c3f6a13788f06:
      image_group_id: I2PD17651
      title: ''
      volume_number: 1
      total_pages: 676
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
